version: '3.7'

services:
  web:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8002
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8002:8002
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=dynasty
      - POSTGRES_PASSWORD=dynasty
      - POSTGRES_DB=dynasty_dev

volumes:
  postgres_data:
